version: "3"

volumes:
  db-volume:
  maildir: {}

services:
  php:
    build: ./docker/php
    volumes:
      - ./api:/var/www/api
    depends_on:
      - db

  # spa:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/front/Dockerfile
  #   tty: true
  #   working_dir: /app
  #   volumes:
  #     - ./front:/app
  #   ports:
  #     - 3000:3000

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: saasus
      POSTGRES_DB: saasus
    # volumes:
    #   - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
